version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dcrm_test
      POSTGRES_USER: johann
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres:
    driver: local
